steps:

- name: 'gcr.io/cloud-builders/bash'
  args:
    - '-c'
    - |
      echo $SHORT_SHA > app-code/git_sha.txt
      echo "$(date -u +'%Y-%m-%d %H:%M:%S UTC')" > app-code/build_time.txt
      echo "Trigger: $TRIGGER_NAME" >> app-code/build_info.txt
      echo "Build ID: $BUILD_ID" >> app-code/build_info.txt

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/bank-repo/bank-dashboard:$SHORT_SHA',
      '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/bank-repo/bank-dashboard:latest',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/bank-repo/bank-dashboard:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/bank-repo/bank-dashboard:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud container clusters get-credentials bank-cluster --region asia-south1 --project $PROJECT_ID
      kubectl apply -f env-config/deployment.yaml
      kubectl apply -f env-config/service.yaml
      kubectl rollout restart deployment/bank-dashboard
      kubectl rollout status deployment/bank-dashboard

options:
  logging: CLOUD_LOGGING_ONLY